### ISSUE TITLE
Icons missing on external url

### ISSUE THREAD

**Issue by Lavve** [karlis-vagalis/hass-lucide-icons#3]
The Lucide icons doesn't show up when accessing HA from an external url. There's nothing in the logs, so not sure how to explain this in more detail, but don't hesitate to ask if you'd need more information.

**Comment by karlis-vagalis** [comment]
Thanks for reporting. Could you please indeed elaborate?

What do you mean by external URL? Which device did you notice this on? Was it working before?. Maybe a screenshot?

**Comment by Lavve** [comment]
Hi, thanks for quick reply.

1. By external URL I mean accessing HA outside my WiFi, In my case accessing HA through DuckDNS
2. This affects all kinds of devices
3. Not sure what you mean by "before", I've only used Lucide icons for about a week and it never worked for me on external URL. Material Design icons (mdi:xxxx) has always worked.

![with_icons](https://github.com/karlis-vagalis/hass-lucide-icons/assets/302588/c38beee0-762a-41c8-a947-c53690a96764)
![without_icons](https://github.com/karlis-vagalis/hass-lucide-icons/assets/302588/6c26e106-c0a2-4d94-8d69-79ef006a3555)

**Comment by karlis-vagalis** [comment]
Could it be, that your reverse proxy is blocking the assets?

This integration exposes the icons at
http(s)://`<your home assistant url>`/lucide_icons/icons/`<icon name>`.svg

For example, something like this:
https://homeassistant.628477.duckdns.org/lucide_icons/icons/home.svg
should open an show the `home` icon. Does that work in your browser?

I am just guessing about possible reasons, as I also access HA from outside my home network and I have not seen the same issue.

**Comment by karlis-vagalis** [comment]
Closed due to no updates
